export const EXERCISE_LIST: string[] = [
  // Peito
  'Supino Reto com Barra',
  'Supino Inclinado com Barra',
  'Supino Declinado com Barra',
  'Supino Reto com Halteres',
  'Supino Inclinado com Halteres',
  'Crucifixo Reto com Halteres',
  'Crucifixo Inclinado com Halteres',
  'Crossover no Cabo',
  'Peck Deck / Voador',
  'Flexão de Braço',
  'Pullover com Halter',

  // Costas
  'Barra Fixa',
  'Puxada Frontal na Polia',
  'Puxada Aberta',
  'Remada Curvada com Barra',
  'Remada Unilateral com Halter',
  'Remada Sentado na Polia',
  'Remada Cavalinho',
  'Levantamento Terra',
  'Levantamento Terra Romeno',
  'Pulldown com Corda',
  'Face Pull',

  // Ombros
  'Desenvolvimento com Barra',
  'Desenvolvimento com Halteres',
  'Desenvolvimento Arnold',
  'Elevação Lateral com Halteres',
  'Elevação Lateral na Polia',
  'Elevação Frontal com Halter',
  'Encolhimento de Ombros',

  // Bíceps
  'Rosca Direta com Barra',
  'Rosca Direta com Halteres',
  'Rosca Alternada com Halteres',
  'Rosca Martelo',
  'Rosca Scott',
  'Rosca Concentrada',
  'Rosca na Polia Baixa',

  // Tríceps
  'Tríceps Testa com Barra',
  'Tríceps na Polia com Corda',
  'Tríceps na Polia com Barra',
  'Tríceps Francês com Halter',
  'Tríceps Coice com Halter',
  'Mergulho no Banco',
  'Fechado',

  // Pernas
  'Agachamento Livre',
  'Agachamento no Smith',
  'Leg Press 45°',
  'Leg Press Horizontal',
  'Cadeira Extensora',
  'Mesa Flexora',
  'Cadeira Abdutora',
  'Cadeira Adutora',
  'Stiff com Barra',
  'Stiff com Halteres',
  'Avanço / Lunge',
  'Agachamento Búlgaro',
  'Panturrilha em Pé',
  'Panturrilha Sentado',
  'Hip Thrust',
  'Glúteo no Cabo',
  'Abdução no Cabo',

  // Core
  'Abdominal Crunch',
  'Abdominal Infra',
  'Prancha',
  'Russian Twist',
  'Abdominal na Polia',
  'Elevação de Pernas',
]
